### ISSUE TITLE
Review & make English localization consistent

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#105]
We agreed to use British English. 

Let's review the current English messages and make sure that all of them are acceptable and consistent.

**Comment by Legend-Dale** [comment]
I have reviewed all the English messages, corrected spelling mistakes and made sure everything is consistent. "zipCode" was the only American English term.

Some classifiers that don't conform to the format such as 
RegistrationPage.firstname=First name (instead of "clientRegister.firstName")
I left untouched (not worth the effort now).
