### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#2]
Somehow we don't have UTF-8 support. Even though I use the UTF-8 versions of the characters ö,ü,ä and ß, they are not displayed...

**Comment by Legend-Dale** [comment]
Solved using UTF-8 hex encoding, see text file "UTF-8 hex codes" in src/main/resources.

**Comment by BujakiAttila** [comment]
What was the final solution? What do you mean by "Solved using UTF-8 hex encoding"? Have you changed the encoding? Or did you add the BOM? Please share your experiences because such problems are quite common. I meet them frequently and it would be nice to know what helped this time. Thanks!

**Comment by Legend-Dale** [comment]
You can have a look into the code. ;)
When I wrote my function there was a hint in my internet example, that one
has to convert the text of the .properties files into UTF-8. I used a shell
command to do that, but all the umlauts were converted to the question mark
symbol. I simply replaced those symbols with the correct hex code e.g.
"\u00df" for 'ß'.

**Comment by BujakiAttila** [comment]
Is this really necessary? This could not be solved with no escape sequences?

Don't get me wrong. I am happy that it works now, but maintaining language files with such escape sequences is going to be really painful in the long run. I think we could open an issue to investigate this opportonity. Maybe it is possible to have proper UTF-8 support with no special escape sequences in the properties file. It would much easier if you could just type "ß" or "ä", instead of always escaping and entering hexadecimal sequences.

What do you think?

**Comment by Legend-Dale** [comment]
Sure, I'll have some internet research tomorrow if that is possible.
If that is not possible I will try to find a program that makes a reliable
conversion.

**Comment by BujakiAttila** [comment]
Ok, cool. Thanks.

I am going to open an issue for this, just to make sure we don't forget it.

**Comment by JonasGroeger** [comment]
I think for now, this is fine.

**Comment by Legend-Dale** [comment]
I've replied to the other mail.
Use native2ascii or implement another method yourself.
I can't come up with something better.

**Comment by Legend-Dale** [comment]
One can use ß, ä, ü and ö now, but make sure the encoding is UTF-8. 
Make sure you editor's encoding uses UTF-8, otherwise you will break it.
