### ISSUE TITLE
Consistent variable names in translation messages_xx.properties

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#40]
Currently, we have **ALL THE STANDARDS**:

```
EmployeePreview.send               ---> Javacase.lowercase
placeholder.placeOfBirth           ---> lowercase.Javacase
placeholder.firstname              ---> lowercase.lowercase
placeholder.Address                ---> lowercase.UpperCamelCase
RegistrationPage.personalDetails   ---> UpperCamelCase.Javacase
RegistrationPage.firstname         ---> UpperCamelCase.lowercase
RegistrationPage.ZipCode           ---> UpperCamelCase.UpperCamelCase
```

It would be great to have everything in a consistent state. Something like

```
client.login.email
client.login.password
client.login.register
client.login.submit
client.logout.confirm

employee.model.firstname
employee.model.bic

form.placeholder.firstname
form.placeholder.password
form.placeholder.password.confirm
```

**Comment by Legend-Dale** [comment]
The way I started the naming system was
<filename>.<attribute>

<filename> so that one would know where the text item is used.
<attribute> so that is is consistent with field and class attributes of
Employee.

Here is an example where I tried to be consistent with the other labels
(familyName not familyname):
 th:text="#{employee.familyName} +#{EmployeeForm.mandatory}"></label>
<input th:field="*{familyName}"  type="text"
class="form-control" th:placeholder="#{placeholder.familyName}" />

We can change this type of formatting things, but it makes sense to me.

Of course this doesn't change the fact that we have a mess.

And it gets even worse: We are having inconsistent duplicates, e.g.:
placeholder.firstname
placeholder.firstName

We should also think of how to label items that are used in several files
(such as the employee or placeholder items).

How about we discuss this during tomorrows developer meeting?

**Comment by BujakiAttila** [comment]
As far as I remember we agreed on to use:

'employee.email' format for the texts for the different business entities
'clientform.submit' format for the texts for the different ViewTemplate specific labels.

I think we also agreed on to prefer having some duplication for the ViewTemplace specifig captions, so we could avoid side effects when changing something.
(For example, you change login.submit text, then you realize that some other captions have also changed in other ViewTemplaters too.)

Is anybody up to fixing these?

**Comment by Matombo** [comment]
everything lowercase? i think that's not good in distinguish things
i would say everything file specific lower case but things that go over several files like employe.email in a stringer format like: Employee.email or even EMPLOYEE.email (Because it's a "constat" / you should really think about where it is used before changing it, also it easyer to find it then with your IDE's search funktion)

**Comment by BujakiAttila** [comment]
Any other comments? I am OK with both "EMLOYEE.email" or "Employee.email" too. Maybe the all uppercase version would be more practical. "Employee.email" looks exactly like the class. That could lead to problems. I know it is used in different context, but still. EMPLOYEE would suggest that is a constant..... Cool idea! :+1:

**Comment by Legend-Dale** [comment]
I like the idea of using lover case for files
employee.edit.button

and capitals for file independent labels:
EMPLOYEE.familyName

But should we use "familyname" or "familyName" (email or eMail)?

**Comment by Matombo** [comment]
well since we have the template naming an alllowercase i would vote for that in the message files too

**Comment by Matombo** [comment]
when i recap right we agreed on:
CONSTANT.valueName
fileName.valueName
