### ISSUE TITLE
User registration - Separate model that will be processed in the ClientService

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#47]
Have a separate Model for the Client registration process. Then, in `/client/register` have something like `@ModelAttribute("clientRegistration") ClientRegistration clientRegistration` and pass that to the service layer which will create the client, put it in the database and voila.

This way we dont leak the Client model to the Controller / Web layer.

**Comment by BujakiAttila** [comment]
It was a great idea, but it is already implemented a different way.

I am closing this issue for now, since I don't think that we are going for this in the future. As far as I know we have different priorities for now. The product owners want us to have the Employee form and the LODAS export working. So I think we should focus on this.
