### ISSUE TITLE
Review message style - Mostly german

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#56]
Since we are working on a business application the messages should not be too casual.

We should review the different messages in our application to make sure that the style of the messages is appropriate.

I refer mostly to the German messages. By mistake I have added a very casual German notification message. Could somebody review the messages and the other contant of the localization files?

Thank you.

**Comment by Legend-Dale** [comment]
I'll have a look at it.

**Comment by Legend-Dale** [comment]
I've gone through the files and made some corrections.

Please don't use umlauts in the message files as long as we have not solved
the encoding issue. It will break on other systems!

There seems to be disagreement on whether to use American or British
English:
E.g. PLZ:
postcode (BE)
zip code (AE)
postal code (BE, Canadian, Australian)

In the excel file it is British English (postcode).
I would personally also go for British English, because that is what we
were taught in school.
I can't tell for other European countries, but I would guess there it is
also British English, isn't it?

Can the non-Germans (and Germans) give an opinion on that?

**Comment by BujakiAttila** [comment]
I think we could use any of them, but when we use ZIP code, let's use it everywhere.

I am also OK with postcode. Since Legend-Dale would like it to be BE, and the excel file is also in British English, let's go for this.

I am closing this issue now and opening a new one for reviewing the localization as we discussed..

**Comment by Legend-Dale** [comment]
I just want to mention that the excel sheet shouldn't be our ultimate
reference, since they are neither entirely consistent, not always correct.

In the meeting we agreed on BE.
