### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#60]
I'm starting to loose the overview in our software, because we have to many files and folders and hidden function calls inbetween. 

New concepts like the security only make it more complicated. 

So I vote for an extensive documentation including a "table of contents", i.e.  what functionality can be found it what file, and the explanation of important concepts like the message files, Principals and so on.

Example: login.html: What happens when I press the submit button? How should I know that I find the answer in SecurityConfiguration.java?

We also need to communicate where to find what documentation.

This is just my opinion. Please discuss.

**Comment by Legend-Dale** [comment]
I am also for descriptions in front of each and every method/function we have.

**Comment by BujakiAttila** [comment]
:+1:

**Comment by Matombo** [comment]
+1 we need that, maybe togather with a refactoring srpint because this can tage some time
also the folder names don't make complete sense to me: for example all "controllers" are in the folder "web"

**Comment by BujakiAttila** [comment]
I think we should be doing this continously. We can't push all refactoring to a theoritical refactoring sprint which is not even sure to happen.

I see that we can't fix everything during one sprint, because we have lot's to do, but still, we have to take care of the code quality and maintainability.

The Controllers are in the "web" folder because the Controllers are used for the web interface. A folder called "Controllers" would be more descriptive, but it is longer. I think this would be the cause of the current folder name. Jonas changed it like this, he prefers short names as far as I know, so this makes sense.

**Comment by JonasGroeger** [comment]
The `web` folder is called that because the guide I used to bootstrap the project was using that naming convention. I agreed with it because not everything in the `web` folder must be controllers, right? For example the `CurrentClientControllerAdvice` is not a controller, yet its related to the web.

I do not vote for an extensive documentation. I vote for an appropriate documentation where nessecary. This means that parts that are important and need clarification should be documented. Not everything.

For this, please open another issue that has more details about what to document.

**Comment by BujakiAttila** [comment]
Since we have already restructured our packages and agreed about future conventions I am going to close this issue.
