### ISSUE TITLE
client login redirection bug

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#70]
1. Open our website with e.g. http://localhost:8080/client/list
->one gets redirected to http://localhost:8080/
After login our website is trying to open "http://localhost:8080/client/list" though and throws an error. 

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sun Jun 14 13:31:17 CEST 2015
There was an unexpected error (type=Not Found, status=404).
No message available

This happens with all invalid addresses.
I guess it would be better always to redirect to the dashboard.

When pressing "Register", goes back to login in the browser and then logs in one gets the following error:
http://localhost:8080/client/js/vendor/bootstrap.min.js

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sun Jun 14 13:36:19 CEST 2015
There was an unexpected error (type=Not Found, status=404).
No message available

But that was the only way I could trigger this kind of error. It already seems to be much more robust than last week.

**Comment by Legend-Dale** [comment]
redirection to
http://localhost:8080/employee/js/vendor/bootstrap.min.js
also occurs if one has e.g. http://localhost:8080/employee/token 
open in one tab and tries to log in in another. 
As far as I know this applies to token, preview and submit.

**Comment by JonasGroeger** [comment]
As I see it, this issue is actually a complaint and an issue, right?

---
First for the complaint: Whenever a user tries to access a page that does not exist, like `/client/list`, a "Whitelabel Error Page" is shown with `Status = 404`. It would be better to redirect the user to another page.

As I see it, this is just what should happen. The error page (in this case 404) is not pretty, I agree. However, a lot of online projects use this kind of error. For example this very website: GitHub. Try to go to [https://github.com/as89dua89sduas89du](https://github.com/as89dua89sduas89du). You wont have any luck being redirected to some other page.

I guess the correct solution is to ask the product owners if they want to have a distinct and nice 404 page.

---

For the bug which is reproducible by these steps

1. Browse `/`
2. Click `Register`
3. Hit "back" button in Browser
4. Login with valid credentials
5. Observe 404

I have fixed it in the [bugfix/70-RegisterBackLogin](https://github.com/JOBAA/amos-ss15-proj4/tree/bugfix/70-RegisterBackLogin) branch. Would be cool if you could verify, @Matombo .

**Comment by Legend-Dale** [comment]
I'm not sure if you understood me correctly: 
When you type in a page that doesn't exist one is redirected to the login.

And if you then login correctly one gets "page not found".
Login should always redirect to the dashboard, not the URL the user typed in.

**Comment by JonasGroeger** [comment]
I don't agree. Sometimes the user enters a url that does exist but has not yet logged in. After login, the user wants to go back to the page anyway so why not redirect him there. Imho this is expected behaviour.

And if browsing to a page that doesen't exist and the user is not logged in will get a 404, this might be a security issue, since maybe later we have something like /client/4/employee/6. You don't want to show 404 here, since that would make the intruder know the client has no employee no 6.

For me, this is a feature, not a bug :)

**Comment by Legend-Dale** [comment]
That the client is directed to the url is expected behaviour.
That he gets an error after loging in isn't.

How about this:
If the url is valid the client is directed to it. If it is invalid he is
redirected to his dashboard (or gets a proper error page).

The problem is that it looks like a bug to the average user when he sees a
404 page after logging in.

**Comment by BujakiAttila** [comment]
I have tried all the described cases. None of them resulted in any unexpected behaviour.

I am closing this issue, since the described problem has been fixed. If there is a separate similar issue, please open a new issue for it, and describe it properly, so it could be reproduced.

I have tested according, both the original script described by Legendale in the first post, and also the one described later by Jonas.

Since none of them resulted in any problem, I am closing this issue.
