### ISSUE TITLE
Hibernate throws error on every start when using test profile

### ISSUE THREAD

**Issue by Matombo** [JOBAA/amos-ss15-proj4#73]
When using the in memory test database on every start there is a error in the log:
2015-06-16 11:57:54.686 ERROR 3789 --- [ost-startStop-1] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000389: Unsuccessful: alter table employee drop constraint FK_j66jdir7lue5le22oqwalye6p
2015-06-16 11:57:54.686 ERROR 3789 --- [ost-startStop-1] org.hibernate.tool.hbm2ddl.SchemaExport  : user lacks privilege or object not found: PUBLIC.EMPLOYEE
the application however runs fine

**Comment by JonasGroeger** [comment]
Does this problem still persist?

**Comment by Matombo** [comment]
jep

**Comment by Matombo** [comment]
i will show it you the next meeting

**Comment by JonasGroeger** [comment]
Did you do any research to find the cause of this error?

Apparently, this is caused by the combination of create-drop and the (empty) in-memory database in the test configuration. [A relevant post can be found here](http://stackoverflow.com/questions/12054422/unsuccessful-alter-table-xxx-drop-constraint-yyy-in-hibernate-jpa-hsqldb-standa).

**Comment by JonasGroeger** [comment]
Did you do any research to find the cause of this error?

Apparently, this is caused by the combination of create-drop and the (empty) in-memory database in the test configuration. [A relevant post can be found here](http://stackoverflow.com/questions/12054422/unsuccessful-alter-table-xxx-drop-constraint-yyy-in-hibernate-jpa-hsqldb-standa).
