### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#91]
"Musterstraße" is being rejected (because of 'ß').

TODO: Implement proper verification, add error messages.

**Comment by BujakiAttila** [comment]
Now most of the validation fields are using the latin predefined char class instead of a-z and A-Z classes. This accepts chars like  'ßáűőúöüó' without problem, but still rejects special charachters like + or %.

Of course some special charachters which are usual in names and street names are accepted. I have agreed about this with the Product Owners. Our reference document says that these fields are alphanumeric, but we still agreed to accept some special chars. These could be filtered out during exportation. (When really needed so.)
